wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: huggingface
    huggingface_version: 4.16.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1646347145
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      4: 3.8.12
      5: 0.12.11
      6: 4.16.2
      8:
      - 1
      - 5
